"""add_days_of_week_and_time_minutes_to_habits

Revision ID: 50d4bf2d94bd
Revises: 369942a88e52
Create Date: 2025-08-08 14:25:14.558875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d4bf2d94bd'
down_revision: Union[str, None] = '369942a88e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('days_of_week', sa.String(length=20), nullable=True))
    op.add_column('habits', sa.Column('time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'time_minutes')
    op.drop_column('habits', 'days_of_week')
    # ### end Alembic commands ###
