"""Add ProcessedCallback table for idempotency

Revision ID: 7093835ceccf
Revises: 87336db24986
Create Date: 2025-08-08 09:47:04.010822

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7093835ceccf"
down_revision: Union[str, None] = "87336db24986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_callbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("callback_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("callback_id", name="uq_callback_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_callbacks")
    # ### end Alembic commands ###
